repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml

template:
  org: nf-core
  name: mspepid
  description: A pipeline for the identification of peptides in mass spectrometry
    data.
  author: Julian Uszkoreit
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  is_nfcore: true
